server:
  port: 9527

spring:
  application:
    name: microservicecloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: dept_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://microservicecloud-dept
          #predicate就是一组匹配规则，让请求找到对应的route来进行处理
          predicates:
            - Path=/dept/get/** # 断言，路径相匹配的进行路由
        - id: timeout_route
          #匹配后提供服务的路由地址
          uri: lb://microservicecloud-dept
          #predicate就是一组匹配规则，让请求找到对应的route来进行处理
          predicates:
            - Path=/dept/timeout/** #断言,路径相匹配的进行路由
        - id: dept_route_default # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://microservicecloud-dept
          #predicate就是一组匹配规则，让请求找到对应的route来进行处理
          predicates:
            - Path=/dept/** # 断言，路径相匹配的进行路由
           #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
           #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
           #- Cookie=username,zzyy
           #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
           #- Host=**.atguigu.com
           #- Method=GET
           #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
           #过滤
         #filters:
           #- AddRequestHeader=X-Request-red, blue

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com    #自定义服务的名称信息
    prefer-ip-address: true                    #访问路径可以显示IP地址



info:
  app.name: springlearning-microservicecloud
  company.name: www.springlearning.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}