server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com    #自定义服务的名称信息
    prefer-ip-address: true                    #访问路径可以显示IP地址

zuul:
  prefix: /springlearning                     #给访问地址添加前缀
  ignored-services: microservicecloud-dept    #忽略在http request中对微服务microservicecloud-dept的直接访问，需要通过下面的映射/mydept**来访问，多个微服务还可以通过 "*"来指定所有的微服务
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: springlearning-microservicecloud
  company.name: www.springlearning.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}