server:
  port: 80

#开启服务降级功能，当服务不可用的时候，会调用对应的FallbackFactory里面提供的服务 参考tk.springlearning.springcloud.service.DeptClientService
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka